apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  creationTimestamp: '2023-11-20T16:54:05Z'
  generation: 12
  managedFields:
    - apiVersion: fleet.cattle.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:branch: {}
          f:clientSecretName: {}
          f:forceSyncGeneration: {}
          f:insecureSkipTLSVerify: {}
          f:paths: {}
          f:repo: {}
          f:targets: {}
      manager: rancher
      operation: Update
      time: '2023-11-20T18:20:05Z'
    - apiVersion: fleet.cattle.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:commit: {}
          f:conditions: {}
          f:desiredReadyClusters: {}
          f:display:
            .: {}
            f:readyBundleDeployments: {}
            f:state: {}
          f:gitJobStatus: {}
          f:lastSyncedImageScanTime: {}
          f:observedGeneration: {}
          f:readyClusters: {}
          f:resourceCounts:
            .: {}
            f:desiredReady: {}
            f:missing: {}
            f:modified: {}
            f:notReady: {}
            f:orphaned: {}
            f:ready: {}
            f:unknown: {}
            f:waitApplied: {}
          f:resources: {}
          f:summary:
            .: {}
            f:desiredReady: {}
            f:nonReadyResources: {}
            f:ready: {}
            f:waitApplied: {}
      manager: fleetcontroller
      operation: Update
      subresource: status
      time: '2023-11-21T08:47:05Z'
  name: petclinic-deployment
  namespace: fleet-default
  resourceVersion: '2237285'
  uid: 83f8d274-bb5d-416c-98f4-1cdcb7fa3c7b
spec:
  branch: {{ .Values.gitRepo.spec.branch }}
  clientSecretName: {{ .Values.gitRepo.spec.clientSecretName }}
  forceSyncGeneration: {{ .Values.gitRepo.spec.forceSyncGeneration }}
  insecureSkipTLSVerify: {{ .Values.gitRepo.spec.insecureSkipTLSVerify }}
  paths: {{ .Values.gitRepo.spec.paths }}
    ## nicht sicher, ob das so geht
  repo: {{ .Values.gitRepo.spec.repo }}
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester